neighbor 127.0.0.1 {
    router-id 10.0.0.1;
	local-address 127.0.0.1;
    local-as 65000;
    peer-as 65001;
    listen 179;

    family {
        bgp-ls bgp-ls;
    }

    announce {
        bgp-ls {
            bgp-ls \
            srv6-sid 7 0 ( 65000 0 192.168.255.1 1 ) \
            origin INCOMPLETE \
            srv6-sid-information [ fd00::1 ] \
            multi-topology-id [ 1 ] \
            next-hop self;
        }
    }
}
